export interface IAlumne {
    id: string,
    nom: string,
    primerCognom: string,
    segonCognom: string,
    dni: string,
    dataNaixemnt: null,
    adreca: string,
    codiPostal: string,
    municipi: string,
    telefon: string,
    email: string,
    nomTutor1: string,
    nomTutor2: string,
    primerCognomTutor1: string,
    primerCognomTutor2: string,
    segonCognomTutor1: string,
    segonCognomTutor2: string,
    nacionnalitat: string,
    paisNaixemet: string,
    lleguaMaterna: string,
    dataArribada: string,
    curs: string,
    ralc: string
}